# Generated by Django 5.0.2 on 2024-12-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, null=True, unique=True)),
                ('type', models.CharField(choices=[('G', 'Зелений'), ('Y', 'Жовтий'), ('R', 'Червоний')], max_length=1)),
                ('gift', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.CreateModel(
            name='MyPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.promocode')),
            ],
            options={
                'verbose_name_plural': 'Мої промокоди',
            },
        ),
    ]
