# Generated by Django 5.0.2 on 2025-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypromocode',
            options={'verbose_name_plural': 'My promo codes'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name_plural': 'Promo codes'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], max_length=1),
        ),
    ]
